version: '3.9'

services:
  app:
    container_name: test-bot
    image: ${IMAGE_ID}
    pull_policy: always
    restart: unless-stopped
    environment:
      TG_TOKEN: ${TG_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
    ports:
      - ${WEBHOOK_PORT}:${WEBHOOK_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
