name: Manual Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    env:
      HOST: ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
      SSH_PORT: ${{ secrets.SERVER_PORT }}
      IMAGE_ID: ghcr.io/paulyakow/test-bot:latest

    runs-on: ubuntu-latest
    steps:
      - name: Create file with deploy key
        env:
          SSH_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key

      - name: Restart container
        run: |
          ssh -i deploy_key -p $SSH_PORT -o StrictHostKeyChecking=no $HOST "\
          export IMAGE_ID=$IMAGE_ID && \
          export TG_TOKEN=${{ secrets.TG_TOKEN }} && \
          bash /srv/start.sh"
