name: Manual Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    env:
      HOST: ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
      SSH_PORT: ${{ secrets.SERVER_PORT }}
      IMAGE_ID: ghcr.io/paulyakow/test-bot:latest
      ENV_FILE_PATH: /srv/.env
      START_CMD: bash /srv/start.sh

    runs-on: ubuntu-latest
    steps:
      - name: Create file with deploy key
        env:
          SSH_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key

      - name: Export envs to server
        run: |
          ssh -i deploy_key -p $SSH_PORT -o StrictHostKeyChecking=no $HOST "\
          echo IMAGE_ID=$IMAGE_ID > $ENV_FILE_PATH && \
          echo TG_TOKEN=${{ secrets.TG_TOKEN }} >> $ENV_FILE_PATH"

      - name: Restart container
        run: |
          ssh -i deploy_key -p $SSH_PORT -o StrictHostKeyChecking=no $HOST "$START_CMD"
