name: Manual Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
      IMAGE_ID: ghcr.io/paulyakow/test-bot:latest

    steps:
      - name: Create file with deploy key
        env:
          SSH_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key

      - name: Remove old image
        run: |
          ssh -i deploy_key -p ${{ secrets.SERVER_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          docker stop test-bot && \
          docker rmi -f ${{ env.IMAGE_ID }}"

      - name: Pull new image
        run: |
          ssh -i deploy_key -p ${{ secrets.SERVER_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          echo ${{ secrets.CR_PAT }} | docker login -u PaulYakow --password-stdin ghcr.io && \
          docker pull ${{ env.IMAGE_ID }}"

      - name: Run container
        run: |
          ssh -i deploy_key -p ${{ secrets.SERVER_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          docker rm test-bot && \
          docker run -d --name test-bot --env TG_TOKEN=${{ secrets.TG_TOKEN }} ${{ env.IMAGE_ID }}"
