name: Push image and deploy
on:
  push:

jobs:
  push:
    env:
      IMAGE_NAME: test-bot
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy:
    needs: push
    env:
      HOST: ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
      SSH_PORT: ${{ secrets.SERVER_PORT }}
      IMAGE_ID: ghcr.io/paulyakow/test-bot:latest
      DEPLOY_DIRECTORY: /srv/test-bot
      ENV_FILE_PATH: /srv/test-bot/.env
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create file with deploy key
        env:
          SSH_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key

      - name: Copy compose file into deploy directory
        run: |
          scp -i deploy_key -P ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ github.workspace }}/docker-compose.yaml ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/

      - name: Create .env file in deploy directory
        run: |
          ssh -i deploy_key -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          echo IMAGE_ID=$IMAGE_ID > ${{ env.ENV_FILE_PATH }} && \
          echo TG_TOKEN=${{ secrets.TG_TOKEN }} >> ${{ env.ENV_FILE_PATH }} && \
          echo WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} >> ${{ env.ENV_FILE_PATH }} && \
          echo WEBHOOK_PORT=${{ secrets.WEBHOOK_PORT }} >> ${{ env.ENV_FILE_PATH }} && \
          chmod 600 ${{ env.ENV_FILE_PATH }}"

      - name: Restart container
        run: |
          ssh -i deploy_key -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          cd ${{ env.DEPLOY_DIRECTORY }} && \
          docker compose down && \
          docker compose up -d
          docker image prune"
